[package]
name = "o4fm-audio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cpal.workspace = true
thiserror.workspace = true
hound.workspace = true

[lints]
workspace = true
