[package]
name = "o4fm-fec"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
o4fm-core.workspace = true
thiserror.workspace = true
labrador-ldpc.workspace = true

[lints]
workspace = true
